"""DSL package — fluent API for authoring test cases."""
from sts2_autotest.dsl.fluent import FluentBuilder, HandlerFn, define
from sts2_autotest.dsl.assertions import (
    advance_dialogue,
    choose_event,
    choose_game_mode,
    choose_map_node,
    combat_basic_policy,
    embark,
    end_turn,
    enemy_hp_decreased_by,
    enemy_took_exact_hits,
    enter_combat,
    game_reached_state,
    give_card,
    has_travelable_node,
    no_crash_detected,
    play_card,
    player_energy_decreased_by,
    player_hp_changed_by,
    return_to_menu,
    select_character,
    set_hp,
    set_seed,
    skip_card_reward,
    start_game,
    start_new_run,
)
from sts2_autotest.dsl.fixtures import FixtureLoader
from sts2_autotest.dsl.handlers import capture_screenshot, log_state

__all__ = [
    "FluentBuilder",
    "FixtureLoader",
    "HandlerFn",
    "advance_dialogue",
    "capture_screenshot",
    "choose_event",
    "choose_game_mode",
    "choose_map_node",
    "combat_basic_policy",
    "define",
    "embark",
    "end_turn",
    "enemy_hp_decreased_by",
    "enemy_took_exact_hits",
    "enter_combat",
    "game_reached_state",
    "give_card",
    "has_travelable_node",
    "log_state",
    "no_crash_detected",
    "play_card",
    "player_energy_decreased_by",
    "player_hp_changed_by",
    "return_to_menu",
    "select_character",
    "set_hp",
    "set_seed",
    "skip_card_reward",
    "start_game",
    "start_new_run",
]
