"""Action descriptor model — decouples action declaration from execution (FR10)."""

from dataclasses import dataclass, field
from typing import Any

from sts2_autotest.common.state import GameScreen, GameState


@dataclass(frozen=True)
class ActionDescriptor:
    """Describes a game action to be executed by the Orchestrator.

    Generated by the Fluent API (dsl/), dispatched by the Orchestrator
    to the adapter. The separation allows new action types without
    changing the orchestration logic.
    """

    action_type: str
    params: dict[str, Any] = field(default_factory=dict)
    expected_state: GameScreen | None = None
    timeout: float = 30.0


@dataclass
class TestResult:
    """Outcome of a single test case execution.

    Unified model used by both Orchestrator and Fluent API.
    - case_id / status / detail: Orchestrator-level fields.
    - failures / state_snapshot: Fluent API assertion fields.
    """

    __test__ = False  # not a pytest test class

    case_id: str
    status: str  # "pass" | "fail" | "crash" | "skip"
    detail: str | None = None
    failures: list[str] = field(default_factory=list)
    state_snapshot: GameState | None = None

    @property
    def passed(self) -> bool:
        return self.status == "pass"
